export const UserActionTypes = {
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAIL: 'REGISTER_FAIL',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  USER_LOADED: 'USER_LOADED',
  LOGOUT: 'LOGOUT',
  LOGOUT_FAIL: 'LOGOUT_FAIL',
  AUTH_ERROR: 'AUTH_ERROR',
};
